[package]
name = "replay-parsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.30.1"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3